### PR TITLE
Add StringSubject.isEqualToIgnoreCase

### PR DESCRIPTION
**Pull request by ooxi**
Sometimes you have to test for string equality while not caring about case sensitivity e.g. when you work with data coming from a case insensitive source (like MySQL with some collation). Includes unit tests.

CLA will follow.

### CODE REVIEW

**Comment by ooxi** [comment]
I signed it!

**Comment by kluever** [comment]
Hi ooxi,

We discussed this idea a long time ago (internally), and these are the notes I was able to dig up:

> Can we come up with a better name?
> * isEqualIgnoringCase(String)?
> * isEqualToIgnoringCase(String)?

> But this raises the usual internationalization questions. We'd need to support ASCII only (by rejecting strings with non-ASCII characters or by just leaving those characters alone?) or else provide an ICU4J extension to Truth.

> We should probably look at potential callers to see how many there are and whether they need i18n.

So I've got a job running right now to see how many callers we'd potentially have for this method...will get back to you.

**Comment by kluever** [comment]
Of all the calls to String.equalsIgnoreCase(String) in google's code base, only 1.25% were being used in conjunction with JUnit's assertTrue/assertFalse, so I'm a bit skeptical about this feature...

Can you explain a bit more about "MySQL with collation" and why it's case insensitive?

**Comment by ooxi** [comment]
A couple of applictions use database schemata with a case insensitive charset, for example OXID eShop (an e-commerce system using MySQL as database backend) or SAP Business One (a business management software using MSSQL as database backend). Both use text identifiers for object identification so if you want to check if order X references customer Y you have to check for "Y" in a case insensitive fashion.

I can understand if this feature gets rejected because of naming or i18n issues. But when developing with a case insensitive source a feature like this sure has many use cases :)

**Comment by kluever** [comment]
Thanks for that additional info. I'm gonna leave this FR open for now. If we get additional, substantial requests for this feature, we'll re-investigate. Thanks again!

**Comment by dimo414** [comment]
I think something like [fuzzy Truth](https://google.github.io/truth/fuzzy.html) is the way forward here, if we decide this is worth doing.

**Comment by ooxi** [comment]
I did not know about fuzzy truth when posting this pull request. I will play around with it but it really looks like covering my usecase quite nicely while being much more general

**Comment by ooxi** [comment]
While Fuzzy Truth handles this problem quite nice it does not solve my use case since `StringSubject` does not implement `comparingValuesUsing`.

**Comment by dimo414** [comment]
Right, Fuzzy Truth is a relatively new feature, and it's currently only for use with collections. By "way forward" I meant that adding similar functionality to `StringSubject` would probably make more sense than adding individual comparison modifiers (e.g. what about `.containsIgnoreCase()`, or locale-aware case-insensitive assertions).

**Comment by ooxi** [comment]
@dimo414 I agree that enabling fuzzy test behavior injection into other subjects would not only solve my use case but be easily expandable and thus quite likely the right way forward

**Comment by cpovirk** [comment]
Case-insensitive comparisons finally made Truth 0.41:
https://google.github.io/truth/api/latest/com/google/common/truth/StringSubject.html#ignoringCase--

**Pull request closed without merging**
