### PR TITLE
Moe sync

### PR DESCRIPTION
**Pull request by ronshapiro**

### CODE REVIEW

**Comment by cpovirk** [comment]
Do you happen to know what the best way for us to handle these is? When I hit "Merge pull request" for the last one, it looks like MOE wasn't able to find an equivalence during my next run. I had to do the rebase thing to straighten it out. And for as long as we keep doing pull requests without "direct" MOE commits, I'd expect for each successive sync to redo all the work of the previous syncs. Maybe all we need is to put `MOE_MIGRATED_REVID=<largest-cl-number-in-the-pull-request>` in the description?

Hmm, I see "Rebase and merge." Let's try that.

**Comment by ronshapiro** [comment]
Hm - I haven't seen that be the case so far when I hit merge. But recently I have used the rebase-and-merge option as well - I even set it as the only option for Dagger. We can change that setting for all of our libraries if we think that's the best option.

**Comment by cpovirk** [comment]
"Rebase and merge" appears to have worked well. It's possible that "Merge pull request" also does the right thing normally but that something weird happened last time. I'll try "Merge pull request" again next time and see what happens. Based on that, we can figure out what to do. Thanks.

**Comment by cpovirk** [comment]
I had to do the rebase again after doing "Merge pull request" on https://github.com/google/truth/pull/280 Probably we should use "Rebase and merge" in general. I've updated our [settings](https://github.com/google/truth/settings) to require that. Thanks for the tip -- I wouldn't have guessed that was possible.

**Pull request merged**
