### PR TITLE
Merge changes from google3

### PR DESCRIPTION
**Pull request by cpovirk**
@cgruber

### CODE REVIEW

**Comment by cpovirk** [comment]
Overriding the CLA check. All authors are Googlers.

**Comment by cpovirk** [comment]
(Oh, right: The previous pull request had the inference bug that you fixed up in https://github.com/google/truth/commit/21abae2ae821ed119d9e9c5d997606d7e3c8b8b9 -- thanks.)

**Comment by cpovirk** [comment]
I suppose that there's no reason that I needed to send this to Christian on his day off :) @kluever, can you have a look?

**Comment by kluever** [comment]
LGTM

**Pull request merged**
