### PR TITLE
Subject for BigDecimal

### PR DESCRIPTION
**Pull request by rikf**
Adds Subject for BigDecimal

### CODE REVIEW

**Comment by ooxi** [comment]
Since this pull request is open for nearly a year now, could you publish your class in an external artefact? I'd like to use it without copy&pasting your sources :)

**Comment by rikf** [comment]
Im not sure why this hasn't been merged in yet, I would be happy to make any changes necessary to get this approved.

**Comment by kluever** [comment]
We have a BigDecimalSubject internally that has been working quite well for us. I'll see if we can get it pushed out soon. Thanks!

**Comment by cgruber** [comment]
I'm on it.  It'll be later today or tomorrow, and I'll be rolling a new
release as well.

**Comment by ooxi** [comment]
:+1:

**Comment by rikf** [comment]
In that case i'm going to close this pull request.

Looking forward to the new release

**Comment by kluever** [comment]
The class was committed in https://github.com/google/truth/commit/7d08f238fbd8f074901a651daedf9e5d70fca4c1

@cgruber is working on a new release that includes it.

**Pull request closed without merging**
