### PR TITLE
MOE Sync

### PR DESCRIPTION
**Pull request by ronshapiro**
@PeteGillinGoogle

### CODE REVIEW

**Comment by PeteGillinGoogle** [comment]
I'm not quite sure why I was tagged on this? Seems like something for either dploch or truth-dev.

**Comment by ronshapiro** [comment]
Whoops, sorry for that mistake. @kluever mind taking quick review?

**Comment by kluever** [comment]
Why don't we do this internally and then sync it outward?

**Comment by kluever** [comment]
LGTM

**Pull request merged**
